version: "3"

services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo_db
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "demo@test.com"
      PGADMIN_DEFAULT_PASSWORD: "demo123"
    ports:
      - 5050:80

volumes:
  pg_data: